### ISSUE TITLE
Failed to run command line:  .\DocumentTranslatorCmd.exe on Win 10

### ISSUE THREAD

**Issue by Tskatom** [MicrosoftTranslator/DocumentTranslator#106]
PS C:\Program Files (x86)\Microsoft Document Translator> .\DocumentTranslatorCmd.exe translatedocuments  /ducuments:D:\tmp\en__RC_2018-01_mr.txt /from:en /to:es
ERROR: Failed to load plugin translatedocuments.
ERROR: An error has occurred.
**************************************
MESSAGE  : Exception has been thrown by the target of an invocation.
SOURCE   : mscorlib
STACK    :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at TranslationAssistant.AutomationToolkit.ConsoleApp.InitializePlugin(String name)
TARGET   : System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

<<INNER EXCEPTION INFO>>
INNER MESSAGE: Could not load file or assembly 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
INNER SOURCE : Tools.TranslationAssistant.TranslationServices.Core
INNER STACK  :    at TranslationAssistant.TranslationServices.Core.TranslationServiceFacade.GetLanguages()
   at TranslationAssistant.TranslationServices.Core.TranslationServiceFacade.Initialize(Boolean force)
   at TranslationAssistant.AutomationToolkit.TranslationPlugins.TranslateDocuments..ctor(ConsoleLogger Logger)
INNER TARGET : Void GetLanguages()
**************************************
ERROR: Unknown functionality.
General Usage:

  DocumentTranslatorCmd.exe [plugin name] [plugin parameters]

  Available plugins are:

      translatexml
      ctftotmx
      translatedocuments
      setcredentials

  Type "DocumentTranslatorCmd.exe [plugin name] /?" for detail help for that plugin.

**Comment by chriswendt1** [comment]
Version mismatch of system.net.http.dll. Took me a while. Installer is now taking the version from the .Net Framework 4.7.2.
