### ISSUE TITLE
Document Translator stops work

### ISSUE THREAD

**Issue by LaoMa1961** [MicrosoftTranslator/DocumentTranslator#111]
The app has problems when starts, sometime just stops, other times it is not possible to choice the languages and several it reports a navigation error. Some screenshots below 
S.O is W10 rel. 10.0.18363 
Thanks for help.

![image](https://user-images.githubusercontent.com/61132391/74627863-05efdb80-518f-11ea-8992-0bf9d628007c.png)
![image](https://user-images.githubusercontent.com/61132391/74627977-5a935680-518f-11ea-81ad-acae9e29e53a.png)
This the error log
"System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'TranslationAssistant.DocumentTranslationInterface.ViewModel.DocumentTranslation' that matches the specified binding constraints threw an exception.' Line number '14' and line position '10'. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TranslationAssistant.TranslationServices.Core.TranslationServiceFacade.IsTranslationServiceReady()
   at TranslationAssistant.DocumentTranslationInterface.ViewModel.DocumentTranslation..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.LoadComponent(Uri resourceLocator)
   at FirstFloor.ModernUI.Windows.DefaultContentLoader.LoadContent(Uri uri)
   at FirstFloor.ModernUI.Windows.DefaultContentLoader.<>c__DisplayClass0_0.<LoadContentAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()"

**Comment by chriswendt1** [comment]
I may have introduced this in the last update. Thanks for reporting.

**Comment by chriswendt1** [comment]
Fixed in version 2.5.5.
